from services.menu_service import (
    get_menu,
    get_available,
    get_category,
    add_item
)

from services.recommendation import get_priority_items,build_recommendations

from state import conversation_context

from schemas import (
    KioskResponse,
    ScreenTypes
)


# =========================================================
# GENERAL MENU
# =========================================================

def handle_menu(user_input, conversation_context, llm):

    if conversation_context["last_category"]:
        menu = get_category(
            conversation_context["last_category"]
        )
    else:
        menu = get_available()

    priority_items = get_priority_items(menu)

    expanded_keywords = [
        "what else",
        "other items",
        "full menu",
        "all items",
        "more options"
    ]

    if any(
        word in user_input.lower()
        for word in expanded_keywords
    ):

        response = (
            "Sure, here are all the available items today:\n\n"
        )

        for item in menu:
            response += (
                f"• {item['name']} – ₹{int(item['price'])}\n"
            )

        response += "\nWhat would you like to order?"

        return response

    priority_text = "\n".join(
        [
            f"{item['name']} – ₹{int(item['price'])}"
            for item in priority_items
        ]
    )

    full_menu_text = "\n".join(
        [
            f"{item['name']} – ₹{int(item['price'])}"
            for item in menu
        ]
    )

    prompt = f"""
You are a Burger King India cashier.

Priority items:
{priority_text}

Full menu:
{full_menu_text}

Rules:
- Mention priority items first naturally
- Briefly mention there are more options
- Do not invent items
- Do not change prices
"""

    response = llm.invoke(prompt)

    return response.content


# =========================================================
# BURGER RECOMMENDATION ENGINE
# =========================================================

#=========================================================
# BUILD COMPLETE BURGER DATASET
# =========================================================

def build_burger_recommendation_data(burgers, cart=None):
    """
    Build the complete burger recommendation dataset.

    The recommendation engine is owned by services.recommendation.
    This function only prepares the response structure expected by
    the existing kiosk/frontend.

    Each recommendation set contains:
        priority   -> max 2
        premium    -> max 2
        additional -> max 4
    """

    if cart is None:
        try:
            from state import conversation_context
            cart = conversation_context.get("cart", [])
        except Exception:
            cart = []

    # -----------------------------------------------------
    # BUILD RECOMMENDATIONS THROUGH THE CENTRAL ENGINE
    # -----------------------------------------------------

    both_priority, both_premium, both_additional = build_recommendations(
        burgers,
        food_type="both",
        cart=cart,
    )

    veg_priority, veg_premium, veg_additional = build_recommendations(
        burgers,
        food_type="veg",
        cart=cart,
    )

    non_veg_priority, non_veg_premium, non_veg_additional = build_recommendations(
        burgers,
        food_type="non veg",
        cart=cart,
    )

    # -----------------------------------------------------
    # THE DEFAULT / BOTH DATASET
    # -----------------------------------------------------

    priority = both_priority
    premium = both_premium
    additional = both_additional

    # -----------------------------------------------------
    # RETURN EXISTING RESPONSE CONTRACT
    #
    # We keep both / veg / non_veg because the current
    # frontend already consumes this structure.
    #
    # The important change is that ALL THREE datasets are
    # now generated by the central recommendation engine.
    # -----------------------------------------------------

    return {
        "priority": priority,
        "premium": premium,
        "additional": additional,

        "both": {
            "priority": both_priority,
            "premium": both_premium,
            "additional": both_additional,
        },

        "veg": {
            "priority": veg_priority,
            "premium": veg_premium,
            "additional": veg_additional,
        },

        "non_veg": {
            "priority": non_veg_priority,
            "premium": non_veg_premium,
            "additional": non_veg_additional,
        },
    }
# =========================================================
# BURGER SELECTION
# =========================================================

def handle_burger_selection(
    burger_type,
    conversation_context
):

    burgers = get_category("burger")

    if not burgers:

        return KioskResponse(
            screen=ScreenTypes.RECOMMENDED_BURGERS,
            message=(
                "Sorry, no burgers are "
                "available right now."
            ),
            data={}
        )

    # -----------------------------------------------------
    # BUILD ONE COMBINED MASTER DATASET
    #
    # The frontend owns the Veg / Non-Veg filter.
    # -----------------------------------------------------

    cart = conversation_context.get("cart", []) if conversation_context else []
    recommendation_data = (
        build_burger_recommendation_data(
            burgers,
            cart=cart
        )
    )

 
    print("BURGER MASTER RECOMMENDATION DATA")
   

    total = (
        len(recommendation_data["priority"])
        + len(recommendation_data["premium"])
        + len(recommendation_data["additional"])
    )

    print(
        "PRIORITY:",
        [
            item["name"]
            for item in recommendation_data["priority"]
        ]
    )

    print(
        "PREMIUM:",
        [
            item["name"]
            for item in recommendation_data["premium"]
        ]
    )

    print(
        "ADDITIONAL:",
        [
            item["name"]
            for item in recommendation_data["additional"]
        ]
    )

    print("TOTAL:", total)

    print("==============================\n")

    # -----------------------------------------------------
    # SELECT DATASET ACCORDING TO USER'S ACTIVE PREFERENCE
    # -----------------------------------------------------

    active_pref = conversation_context.get("food_preference")
    if burger_type in ("veg", "non_veg", "both"):
        chosen_type = burger_type
    elif active_pref in ("veg", "non_veg"):
        chosen_type = active_pref
    else:
        chosen_type = "both"

    chosen = recommendation_data.get(chosen_type, recommendation_data["both"])

    selected = (
        chosen["priority"]
        + chosen["premium"]
        + chosen["additional"]
    )

    conversation_context["last_offer"] = [
        item["name"]
        for item in selected
    ]

    # -----------------------------------------------------
    # NATURAL OPENING MESSAGE
    # -----------------------------------------------------

    message_parts = []

    if chosen["priority"]:

        message_parts.append(
            f"I'd recommend our "
            f"{chosen['priority'][0]['name']}."
        )

    if chosen["premium"]:

        message_parts.append(
            f"If you're looking for something premium, "
            f"we also have our "
            f"{chosen['premium'][0]['name']}."
        )

    if chosen["additional"]:

        message_parts.append(
            "We also have more options in burgers "
            "if you'd like to explore them."
        )

    message = " ".join(
        message_parts
    )

    # -----------------------------------------------------
    # RETURN ONE MASTER DATASET
    # -----------------------------------------------------

    return KioskResponse(
        screen=ScreenTypes.RECOMMENDED_BURGERS,
        message=message,
        data={
            "selected_type": chosen_type,

            "all_burgers": burgers,

            "priority": chosen["priority"],
            "premium": chosen["premium"],
            "additional": chosen["additional"],
            "both": recommendation_data["both"],
            "veg": recommendation_data["veg"],
            "non_veg": recommendation_data["non_veg"]
        }
    )


# =========================================================
# FULL MENU
# =========================================================

def handle_full_menu(conversation_context):

    if conversation_context["last_category"]:

        menu = get_category(
            conversation_context["last_category"]
        )

        priority = get_priority_items(menu)

        remaining = [
            item
            for item in menu
            if item not in priority
        ]

        if not remaining:

            return (
                f"That's all we currently have in "
                f"{conversation_context['last_category']}."
            )

        response = "Besides those, we also have:\n\n"

        for item in remaining:

            response += (
                f"• {item['name']} – ₹{int(item['price'])}\n"
            )

        response += (
            "\nThat completes our available "
            "options in this category."
        )

        return response

    menu = get_available()

    response = (
        "Sure, here are all available items today:\n\n"
    )

    for item in menu:

        response += (
            f"• {item['name']} – ₹{int(item['price'])}\n"
        )

    response += (
        "\nThat's everything currently available. "
        "What would you like to order?"
    )

    return response


# =========================================================
# CATEGORY
# =========================================================

def handle_category(
    category,
    conversation_context
):

    category_map = {
        "beverage": "drink",
        "beverages": "drink",
        "drinks": "drink",
        "burger": "burger",
        "burgers": "burger",
        "side": "side",
        "sides": "side",
        "dessert": "dessert",
        "desserts": "dessert"
    }

    category = category_map.get(
        category.lower(),
        category.lower()
    )

    conversation_context["last_category"] = category

    if category == "burger":

        return handle_burger_selection(
            "both",
            conversation_context
        )

    if category == "drink":

        return handle_drink_selection(
            conversation_context
        )

    if category == "side":

        return handle_side_selection(
            conversation_context
        )

    if category == "dessert":

        return handle_dessert_selection(
            conversation_context
        )

    return "Unknown category."


# =========================================================
# MORE OPTIONS
# =========================================================

def handle_more_options():

    if conversation_context["last_category"]:

        menu = get_category(
            conversation_context["last_category"]
        )

    else:

        menu = get_available()

    priority_items = get_priority_items(menu)

    remaining_items = [
        item
        for item in menu
        if item not in priority_items
    ]

    if not remaining_items:

        return (
            f"That's all we currently have in "
            f"{conversation_context['last_category']}."
        )

    response = "Besides those, we also have:\n\n"

    for item in remaining_items:

        response += (
            f"• {item['name']} – ₹{int(item['price'])}\n"
        )

    response += (
        "\nWould you like to try any of these?"
    )

    return response


# =========================================================
# OTHER CATEGORY RECOMMENDATIONS
# =========================================================

def build_filtered_master_recommendation_data(
    items,
    filter_field,
    filter_values,
    cart=None
):

    grouped = {}

    for filter_value in filter_values:

        filtered_items = [
            item
            for item in items
            if item.get(filter_field, "")
            .lower()
            .replace("_", " ")
            .strip()
            == filter_value
        ]

        grouped[filter_value] = build_recommendations(
            filtered_items,
            filter_value,
            cart=cart
        )

    priority = []
    premium = []
    additional = []

    # 2 priority + 2 premium from every filter value,
    # interleaved into one master list.
    for index in range(2):

        for filter_value in filter_values:

            recommendations = grouped[filter_value]

            if index < len(recommendations[0]):
                priority.append(
                    recommendations[0][index]
                )

            if index < len(recommendations[1]):
                premium.append(
                    recommendations[1][index]
                )

    # 4 additional items from every filter value,
    # interleaved into one master list.
    for index in range(4):

        for filter_value in filter_values:

            recommendations = grouped[filter_value]

            if index < len(recommendations[2]):
                additional.append(
                    recommendations[2][index]
                )

    return {
        "priority": priority,
        "premium": premium,
        "additional": additional
    }


# =========================================================
# CATEGORY RECOMMENDATION RESPONSE
# =========================================================

def build_category_response(
    category,
    title,
    screen,
    conversation_context,
    filter_field=None,
    filter_values=None,
    all_items_key=None
):

    items = get_category(category)

    if not items:

        return KioskResponse(
            screen=screen,
            message=(
                f"Sorry, no {title.lower()} "
                f"are available right now."
            ),
            data={}
        )

    cart = conversation_context.get("cart", [])

    # Build the normal category dataset first.
    if filter_field and filter_values:
        recommendation_data = build_filtered_master_recommendation_data(
            items, filter_field, filter_values, cart=cart
        )
    else:
        priority, premium, additional = build_recommendations(items, cart=cart)
        recommendation_data = {
            "priority": priority,
            "premium": premium,
            "additional": additional
        }

    # Build dietary datasets from the database foodType field.
    food_type_items = [item for item in items if item.get("foodType") is not None]
    if food_type_items:
        veg_items = [item for item in food_type_items if str(item.get("foodType", "")).lower().replace("_", " ").strip() == "veg"]
        non_veg_items = [item for item in food_type_items if str(item.get("foodType", "")).lower().replace("_", " ").strip() in ("non veg", "non_veg")]
        dietary_data = {
            "both": {"priority": recommendation_data["priority"], "premium": recommendation_data["premium"], "additional": recommendation_data["additional"]},
            "veg": dict(zip(("priority", "premium", "additional"), build_recommendations(veg_items, "veg", cart=cart))),
            "non_veg": dict(zip(("priority", "premium", "additional"), build_recommendations(non_veg_items, "non veg", cart=cart))),
        }
        dietary_data["veg"]["priority"] = dietary_data["veg"]["priority"][:2]
        dietary_data["veg"]["premium"] = dietary_data["veg"]["premium"][:2]
        dietary_data["veg"]["additional"] = dietary_data["veg"]["additional"][:4]
        dietary_data["non_veg"]["priority"] = dietary_data["non_veg"]["priority"][:2]
        dietary_data["non_veg"]["premium"] = dietary_data["non_veg"]["premium"][:2]
        dietary_data["non_veg"]["additional"] = dietary_data["non_veg"]["additional"][:4]
    else:
        dietary_data = {"both": {"priority": recommendation_data["priority"], "premium": recommendation_data["premium"], "additional": recommendation_data["additional"]}}

    active_pref = conversation_context.get("food_preference")
    chosen = dietary_data.get(active_pref, dietary_data["both"]) if active_pref in ("veg", "non_veg") else dietary_data["both"]
    priority, premium, additional = chosen["priority"], chosen["premium"], chosen["additional"]
    selected = priority + premium + additional
    conversation_context["last_offer"] = [item["name"] for item in selected]

    message_parts = []

    if priority:

        message_parts.append(
            f"I'd recommend our "
            f"{priority[0]['name']}."
        )

    if premium:

        message_parts.append(
            f"For something premium, we also have "
            f"{premium[0]['name']}."
        )

    if additional:

        message_parts.append(
            f"We also have more {title.lower()} "
            f"options if you'd like to explore them."
        )

    message = " ".join(
        message_parts
    )

    response_data = {
        "priority": priority,
        "premium": premium,
        "additional": additional
    }

    if filter_values:
        response_data["selected_type"] = "both"

    if all_items_key:
        response_data[all_items_key] = items

    return KioskResponse(
        screen=screen,
        message=message,
        data={
            **response_data,
            "category": category,
            "priority": priority,
            "premium": premium,
            "additional": additional,
            **dietary_data,
        }
    )


# =========================================================
# DRINKS
# =========================================================

def handle_drink_selection(
    conversation_context
):

    return build_category_response(
        category="drink",
        title="Drinks",
        screen=ScreenTypes.RECOMMENDED_DRINKS,
        conversation_context=conversation_context,
        filter_field="type",
        filter_values=["hot", "cold"],
        all_items_key="all_drinks"
    )

# =========================================================
# SIDES
# =========================================================

def handle_side_selection(
    conversation_context
):

    return build_category_response(
        category="side",
        title="Sides",
        screen=ScreenTypes.RECOMMENDED_SIDES,
        conversation_context=conversation_context,
        filter_field="foodType",
        filter_values=["veg", "non veg"],
        all_items_key="all_sides"
    )

# =========================================================
# DESSERTS
# =========================================================

def handle_dessert_selection(
    conversation_context
):

    return build_category_response(
        category="dessert",
        title="Desserts",
        screen=ScreenTypes.RECOMMENDED_DESSERTS,
        conversation_context=conversation_context,
        all_items_key="all_desserts"
    )