#Hemnath's
import io
import os
import subprocess
import tempfile
import uuid
from pathlib import Path
from services.cashier_agent import run_cashier_agent

import numpy as np
import soundfile as sf
from dotenv import load_dotenv
from fastapi import FastAPI, File, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from kokoro import KPipeline
from pydantic import BaseModel

from kiosk_service import process_message
from schemas import KioskResponse
from screen_controls import get_screen_controls
from services.cart_service import (
    add_item as cart_add_item,
    add_meal,
    clear_cart,
    complete_order,
    get_cart,
    update_cart_item,
)
from services.meal_service import get_meal_options
from services.menu_service import (
    add_item,
    get_available,
    get_category,
    get_menu,
)
from state import conversation_context, reset_conversation


load_dotenv()


print("INITIALIZING KOKORO TTS...")

tts_pipeline = KPipeline(
    lang_code="a"
)
 
print("KOKORO TTS READY")


app = FastAPI()

from app.api.v1.recommendations import router as recommendations_router
from app.infrastructure.repositories.catalog_repository import (
    SQLAlchemyCatalogRepository,
    get_category_default_image,
)
from app.application.cart_service import CartService
from app.intelligence.recommendation.llm_merchandising_engine import LLMMerchandisingEngine
from app.intelligence.recommendation.session_learner import SessionLearner
from app.intelligence.recommendation.heuristics.circadian_clock import CircadianCravingAnalyzer
from app.intelligence.recommendation.llm_merchandising_engine import (
    record_impressions,
    get_impression_penalty,
)

_catalog_repo = SQLAlchemyCatalogRepository()
_cart_service = CartService(_catalog_repo)
_merchandising_engine = LLMMerchandisingEngine(_catalog_repo)

app.include_router(recommendations_router)

@app.on_event("startup")
async def startup_prewarm():
    try:
        import asyncio
        from repositories.menu_repository import fetch_menu_rows
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, fetch_menu_rows)
        print("CATALOG IN-MEMORY CACHE PRE-WARMED SUCCESSFULLY")
    except Exception as e:
        print(f"Warning: Failed to pre-warm catalog cache: {e}")


from app.config.settings import get_settings
_settings = get_settings()

app.add_middleware(
    CORSMiddleware,
    allow_origins=_settings.allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ------------------------------------------------------------------
# CORS-safe global exception handler.
# Starlette's CORSMiddleware only adds headers to 2xx / 4xx responses
# generated by the routing layer. Unhandled 500s bypass it — the
# browser then sees no CORS header and reports a CORS error instead
# of the actual 500.  This handler intercepts every unhandled
# exception, returns a proper JSON 500, and manually injects the
# Access-Control-Allow-Origin header so the browser can read the
# error response without a CORS block.
# ------------------------------------------------------------------
CORS_ALLOW_ORIGINS = set(_settings.allowed_origins)

@app.exception_handler(Exception)
async def global_cors_safe_exception_handler(request: Request, exc: Exception):
    origin = request.headers.get("origin", "")
    headers = {}
    if origin in CORS_ALLOW_ORIGINS:
        headers["Access-Control-Allow-Origin"] = origin
        headers["Access-Control-Allow-Credentials"] = "true"
        headers["Access-Control-Allow-Methods"] = "*"
        headers["Access-Control-Allow-Headers"] = "*"
    error_type = type(exc).__name__
    error_msg = str(exc)
    # Truncate very long tracebacks in the response body
    if len(error_msg) > 400:
        error_msg = error_msg[:400] + "..."
    print(f"UNHANDLED EXCEPTION [{error_type}]: {error_msg}")
    return JSONResponse(
        status_code=500,
        content={"error": error_type, "detail": error_msg},
        headers=headers,
    )


class MessageRequest(BaseModel):
    message: str


class AddToCartRequest(BaseModel):
    item_name: str
    quantity: int = 1


def _filter_sections_by_pref(sections: list[dict], preference: str | None) -> list[dict]:
    if not preference or preference.lower() == "both":
        return sections
    pref_norm = preference.lower().strip()
    filtered = []
    for sec in sections:
        prods = []
        for p in sec.get("products", []):
            ptype = str(p.get("type") or p.get("foodType") or p.get("food_type") or "").lower()
            pname = str(p.get("name") or "").lower()
            if pref_norm == "veg":
                if ptype == "veg" or ("non" not in ptype and not any(k in pname for k in ["chicken", "wings", "nugget"])):
                    prods.append(p)
            elif "non" in pref_norm:
                if "non" in ptype or any(k in pname for k in ["chicken", "wings", "nugget"]):
                    prods.append(p)
        if prods:
            new_sec = dict(sec)
            new_sec["products"] = prods
            filtered.append(new_sec)
    return filtered


async def _compute_dynamic_category_merchandising(category: str, session_id: str = "default-kiosk-session", branch_id: int = 1, preference: str | None = None):
    cat_norm = category.lower().rstrip("s")
    if cat_norm in ("burger", "burgers"):
        cat_norm = "burger"
    elif cat_norm in ("drink", "drinks", "beverage", "beverages"):
        cat_norm = "drink"
    elif cat_norm in ("side", "sides", "snack", "snacks"):
        cat_norm = "side"
    elif cat_norm in ("dessert", "desserts", "sweet", "sweets"):
        cat_norm = "dessert"

    target_session = session_id or "default-kiosk-session"
    items = await _catalog_repo.get_by_category(cat_norm, branch_id)
    if not items:
        items = await _catalog_repo.get_all_available(branch_id)

    cart = await _cart_service.get_cart(target_session)
    cart_item_ids = {line.item_id for line in cart.lines}
    cart_categories = [line.category.lower() for line in cart.lines]
    cart_item_names = [line.item_name.lower() for line in cart.lines]

    circadian_phase = CircadianCravingAnalyzer.get_current_circadian_phase()
    phase_labels = {
        "morning": "🌅 Morning Warm-Up",
        "lunch": "☀️ Lunch Rush",
        "afternoon_snack": "🍟 Afternoon Snack",
        "dinner": "🍔 Dinner Rush",
        "late_night": "🌙 Late-Night Comfort",
    }
    circadian_badge = phase_labels.get(circadian_phase, "⭐ Chef's Picks")

    profile = SessionLearner.update_from_cart(target_session, cart.lines)
    intent_mode = profile.basket_intent_mode

    if preference:
        pref_l = preference.lower().strip()
        if pref_l in ("veg", "non veg", "non_veg"):
            profile.dietary_lock = "veg" if pref_l == "veg" else "non_veg"
        elif pref_l == "both":
            profile.dietary_lock = None

    effective_dietary = (preference or profile.dietary_lock or "").lower()

    has_spicy_cart = any("peri" in n or "spicy" in n or "fiery" in n for n in cart_item_names)
    has_burger_cart = any("burger" in c for c in cart_categories)
    has_drink_cart = any("drink" in c or "beverage" in c or "coke" in n or "pepsi" in n for c, n in zip(cart_categories, cart_item_names))

    context_headline = "Curated For You"
    context_subline = "Hand-picked favorites to complete your meal"

    if intent_mode == "premium_beverage":
        context_headline = "✨ Essential Bites to Pair with Your Drink"
        context_subline = "Flame-grilled burgers & golden sides to complete your beverage"
    elif intent_mode == "budget_hunter":
        context_headline = "⭐ Smart Value Deals & Micro-Upgrades"
        context_subline = "Unbeatable taste that respects your wallet"
    elif circadian_phase == "morning":
        context_headline = "🌅 Morning Warm-Up & Breakfast Picks"
        context_subline = "Fresh energizing brew & light morning favorites"
    elif circadian_phase == "late_night":
        context_headline = "🌙 Late-Night Indulgence & Comfort Food"
        context_subline = "Satisfy your midnight cravings with rich, warm comfort"

    dismissed_ids = getattr(profile, "dismissed_item_ids", set()) or set()
    excluded_ids = cart_item_ids | dismissed_ids
    valid_candidates = [it for it in items if it.id not in excluded_ids]

    if "veg" in effective_dietary and "non" not in effective_dietary:
        valid_candidates = [it for it in valid_candidates if it.food_type and "veg" in str(it.food_type).lower() and "non" not in str(it.food_type).lower()]
    elif "non" in effective_dietary:
        valid_candidates = [it for it in valid_candidates if it.food_type and "non" in str(it.food_type).lower()]

    if not valid_candidates:
        from app.intelligence.recommendation.gatekeeper import Gatekeeper
        valid_candidates = Gatekeeper.handle_zero_candidates_fallback(items, limit=6)
        if "veg" in effective_dietary and "non" not in effective_dietary:
            valid_candidates = [it for it in valid_candidates if it.food_type and "veg" in str(it.food_type).lower() and "non" not in str(it.food_type).lower()]

    cart_dicts = [
        {"id": l.item_id, "name": l.item_name, "unit_price": float(l.unit_price.amount), "category": str(l.category)}
        for l in cart.lines
    ]
    llm_merch = await _merchandising_engine.improvise_merchandising(
        session_id=target_session,
        category=cat_norm,
        cart_items=cart_dicts,
        candidates=valid_candidates,
        circadian_phase=circadian_phase,
        session_behavior={"removed_item": profile.last_removed_item, "mode": intent_mode},
        dietary_preference=profile.dietary_lock,
    )

    llm_headline = llm_merch.get("headline") or context_headline
    llm_subline = llm_merch.get("subline") or context_subline
    manifestation_nudge = llm_merch.get("manifestation_nudge") or "🔥 Hand-crafted fresh for you"
    llm_items = llm_merch.get("items", {})

    scored = []
    for it in valid_candidates:
        p_val = float(it.price.amount)
        name_lower = it.name.lower()
        score = 1.0
        badge = "🔥 Top Pick"
        reason = "Customer favorite at Burger King"

        circ_mult, _ = CircadianCravingAnalyzer.evaluate_circadian_multiplier(it)
        score *= circ_mult

        score *= get_impression_penalty(target_session, it.id)

        if intent_mode == "premium_beverage":
            if cat_norm in ("burger", "side"):
                score += 1.30
                badge = "🍔 Essential Meal Bite"
                reason = "Essential flame-grilled pairing to complete your drink"
            elif cat_norm == "drink":
                score *= 0.40
        elif intent_mode == "budget_hunter":
            if p_val <= 69.0:
                score += 1.50
                badge = "⭐ Unbeatable Value"
                reason = "Pocket-friendly treat packed with taste"
            elif p_val <= 100.0:
                score += 0.80
                badge = "⭐ Great Value"
                reason = "Hearty flavor that stays easy on your wallet"
            elif p_val > 140.0:
                score *= 0.15
        elif has_spicy_cart and any(k in name_lower for k in ["shake", "sundae", "coffee", "float", "ice"]):
            score += 0.95
            badge = "❄️ Calms The Spice"
            reason = "Cooling soothing pair to soothe your spicy dish"
        elif has_burger_cart and not has_drink_cart and cat_norm in ("drink", "beverage"):
            score += 0.85
            badge = "🥤 Perfect Burger Wash"
            reason = "Refreshing sip to balance your burger"
        elif any(k in name_lower for k in ["whopper", "royale", "cold coffee", "peri peri fries"]):
            score += 0.50
            badge = "🔥 Signature Bestseller"
            reason = "King of the menu, flame-grilled perfection"
        elif any(k in name_lower for k in ["sundae", "shake", "lava"]):
            score += 0.40
            badge = "✨ Sweet Indulgence"
            reason = "Rich velvety dessert to complete your meal"

        it_merch = llm_items.get(it.id, {})
        if it_merch:
            score *= it_merch.get("synergy_score", 1.0)
            if it_merch.get("badge"):
                badge = it_merch["badge"]
            if it_merch.get("sensory_rationale"):
                reason = it_merch["sensory_rationale"]

        scored.append((score, badge, reason, it, it_merch))

    scored.sort(key=lambda x: x[0], reverse=True)

    result = []
    for s, badge, reason, it, it_merch in scored:
        fallback = get_category_default_image(it.category, it.name)
        img = it.image or fallback
        if img and not img.startswith("http") and not img.startswith("/"):
            img = "/" + img
        meal_img = it.meal_image or img
        if meal_img and not meal_img.startswith("http") and not meal_img.startswith("/"):
            meal_img = "/" + meal_img
        is_veg = bool(it.food_type and "veg" in str(it.food_type).lower() and "non" not in str(it.food_type).lower())

        has_micro_deal = it_merch.get("has_micro_deal", False)
        orig_price = it_merch.get("original_price", float(it.price.amount))
        offer_price = it_merch.get("offer_price", float(it.price.amount))
        discount_pct = it_merch.get("discount_pct", 0)
        deal_tag = it_merch.get("deal_tag")

        result.append({
            "id": it.id,
            "name": it.name,
            "price": offer_price if has_micro_deal else orig_price,
            "original_price": orig_price,
            "offer_price": offer_price,
            "has_micro_deal": has_micro_deal,
            "discount_pct": discount_pct,
            "deal_tag": deal_tag,
            "image": img,
            "meal_image": meal_img,
            "category": str(it.category.value if hasattr(it.category, "value") else it.category),
            "type": "veg" if is_veg else "non veg",
            "foodType": "veg" if is_veg else "non veg",
            "shortDescription": it.short_description or it.name,
            "badge": badge,
            "synergy_reason": reason,
            "is_meal_available": it.is_meal_available,
        })

    record_impressions(target_session, [x["id"] for x in result[:8]])

    return {
        "all_serialized": result,
        "headline": llm_headline,
        "subline": llm_subline,
        "manifestation_nudge": manifestation_nudge,
        "circadian_badge": circadian_badge,
        "intent_mode": intent_mode,
    }


@app.post("/session/preference")
async def set_session_preference(payload: dict):
    sid = payload.get("session_id", "default-kiosk-session")
    pref = (payload.get("preference") or "both").strip().lower()
    SessionLearner.set_explicit_dietary_override(sid, pref)
    profile = SessionLearner.get_or_create_profile(sid)
    return {
        "success": True,
        "session_id": sid,
        "preference": pref,
        "dietary_lock": profile.dietary_lock,
        "is_explicit_override": profile.is_explicit_override,
    }


@app.post("/session/reset")
async def reset_session_endpoint(payload: dict):
    sid = payload.get("session_id", "default-kiosk-session")
    SessionLearner.clear_profile(sid)
    try:
        await _cart_service.clear_cart(sid)
    except Exception:
        pass
    return {"success": True, "session_id": sid, "message": "Session reset successfully"}


@app.get("/menu/spotlight/{category}")
async def get_menu_spotlight(category: str, session_id: str = "default-kiosk-session", branch_id: int = 1, preference: str | None = None):
    if preference:
        p = SessionLearner.get_or_create_profile(session_id)
        if preference.lower() in ("veg", "non veg", "non_veg"):
            p.dietary_lock = "veg" if preference.lower() == "veg" else "non_veg"
    data = await _compute_dynamic_category_merchandising(category, session_id, branch_id, preference=preference)
    return {
        "success": True,
        "category": category,
        "headline": data["headline"],
        "subline": data["subline"],
        "manifestation_nudge": data["manifestation_nudge"],
        "circadian_badge": data["circadian_badge"],
        "intent_mode": data["intent_mode"],
        "spotlight": data["all_serialized"][:4],
    }


@app.get("/recommendations/category/{category}")
async def get_category_recommendations(
    category: str,
    session_id: str = "default-kiosk-session",
    branch_id: int = 1,
    preference: str | None = None,
):
    data = await _compute_dynamic_category_merchandising(category, session_id, branch_id, preference=preference)
    all_items = data["all_serialized"]
    intent_mode = data.get("intent_mode", "explorer")

    veg_items = [i for i in all_items if i.get("foodType") == "veg" or i.get("type") == "veg"]
    non_veg_items = [i for i in all_items if i.get("foodType") != "veg" and i.get("type") != "veg"]

    def build_set(lst):
        pool = lst if lst else all_items
        prio = pool[:2] if len(pool) >= 2 else (pool * 2)[:2]
        remaining = [i for i in pool if i["id"] not in {p["id"] for p in prio}]
        if not remaining:
            remaining = pool
        if intent_mode == "budget_hunter":
            prem_cands = [i for i in remaining if i.get("original_price", 999) <= 140]
            prem = prem_cands[:2] if len(prem_cands) >= 2 else (prem_cands + remaining)[:2]
        else:
            prem = remaining[:2] if len(remaining) >= 2 else (remaining + pool)[:2]
        used_ids = {p["id"] for p in prio} | {p["id"] for p in prem}
        add = [i for i in pool if i["id"] not in used_ids][:4]
        if len(add) < 4:
            extra = [i for i in pool if i["id"] not in {a["id"] for a in add}]
            add = (add + extra + pool)[:4]
        return {
            "priority": prio,
            "premium": prem,
            "additional": add,
        }

    both_prio = []
    if veg_items:
        both_prio.append(veg_items[0])
    if non_veg_items:
        both_prio.append(non_veg_items[0])
    if len(both_prio) < 2:
        both_prio = all_items[:2]

    remaining_both = [i for i in all_items if i not in both_prio]
    if intent_mode == "budget_hunter":
        both_prem_cands = [i for i in remaining_both if i.get("original_price", 999) <= 140]
        both_prem = both_prem_cands[:2] if len(both_prem_cands) >= 2 else (both_prem_cands + remaining_both)[:2]
    else:
        both_prem = remaining_both[:2] if len(remaining_both) >= 2 else (remaining_both + all_items)[:2]

    both_add = [i for i in all_items if i not in both_prio and i not in both_prem][:4]

    prof = SessionLearner.get_or_create_profile(session_id)
    eff_pref = (preference or prof.dietary_lock or "").lower().strip()

    if eff_pref == "veg" and veg_items:
        top_set = build_set(veg_items)
        prio, prem, add = top_set["priority"], top_set["premium"], top_set["additional"]
    elif "non" in eff_pref and non_veg_items:
        top_set = build_set(non_veg_items)
        prio, prem, add = top_set["priority"], top_set["premium"], top_set["additional"]
    else:
        prio = both_prio if both_prio else all_items[:2]
        prem = both_prem if both_prem else (all_items[2:4] if len(all_items) >= 4 else all_items[:2])
        add = both_add if both_add else (all_items[4:8] if len(all_items) >= 8 else all_items[:4])

    return {
        "success": True,
        "category": category,
        "headline": data["headline"],
        "subline": data["subline"],
        "manifestation_nudge": data["manifestation_nudge"],
        "circadian_badge": data["circadian_badge"],
        "intent_mode": intent_mode,
        "priority": prio,
        "premium": prem,
        "additional": add,
        "both": {
            "priority": both_prio,
            "premium": both_prem,
            "additional": both_add,
        },
        "veg": build_set(veg_items) if veg_items else build_set(all_items),
        "non_veg": build_set(non_veg_items) if non_veg_items else build_set(all_items),
    }


@app.get("/health")
def health():
    return {
        "status": "running"
    }


@app.post("/session/start")
def start_session():
    session_id = str(uuid.uuid4())

    reset_conversation(session_id)

    print("SESSION STARTED")
    print(conversation_context)

    return {
        "success": True,
        "session_id": session_id,
        "message": "Welcome to Burger King",
        "voice_enabled": True,
    }


@app.post("/screen")
def update_screen(request: dict):
    screen = request.get("screen")

    if not screen:
        return {
            "success": False,
            "message": "screen is required",
        }

    conversation_context["current_screen"] = screen

    conversation_context["available_controls"] = (
        get_screen_controls(screen)
    )

    print("SCREEN SYNC:", screen)

    print(
        "AVAILABLE CONTROLS:",
        conversation_context["available_controls"],
    )

    return {
        "success": True,
        "screen": screen,
        "available_controls": (
            conversation_context["available_controls"]
        ),
    }


@app.get("/menu/burgers")
def burgers(preference: str | None = None):
    sections = get_menu("burger")
    return _filter_sections_by_pref(sections, preference)


@app.get("/menu/drinks")
def drinks(preference: str | None = None):
    sections = get_menu("drink")
    return _filter_sections_by_pref(sections, preference)


@app.get("/menu/sides")
def sides(preference: str | None = None):
    sections = get_menu("side")
    return _filter_sections_by_pref(sections, preference)


@app.get("/menu/desserts")
def desserts(preference: str | None = None):
    sections = get_menu("dessert")
    return _filter_sections_by_pref(sections, preference)


@app.get("/cart")
def cart():
    return get_cart()


@app.post("/message")
def message(request: MessageRequest):
    print("USER MESSAGE:", request.message)

    # Clear any response left by a previous agent turn.
    conversation_context.pop(
        "_last_kiosk_response",
        None,
    )

    msg_clean = request.message.lower().strip()

    # Fast-path for direct category requests (1ms response)
    category_map = {
        "burger": "burger",
        "burgers": "burger",
        "whopper": "burger",
        "drink": "drink",
        "drinks": "drink",
        "beverage": "drink",
        "beverages": "drink",
        "side": "side",
        "sides": "side",
        "fries": "side",
        "dessert": "dessert",
        "desserts": "dessert",
    }
    for kw, cat in category_map.items():
        if f"i want a {kw}" in msg_clean or f"i want {kw}" in msg_clean or msg_clean == kw:
            from services.menuservice import handle_category
            kiosk_resp = handle_category(cat, conversation_context)
            if hasattr(kiosk_resp, "model_dump"):
                return kiosk_resp.model_dump()
            elif isinstance(kiosk_resp, dict):
                return kiosk_resp

    try:
        agent_response = run_cashier_agent(
            request.message,
            conversation_context,
        )
    except Exception as exc:
        print(f"CASHIER AGENT ERROR: {exc}")
        agent_response = "Welcome to Burger King! How can I help you today?"

    kiosk_response = conversation_context.pop(
        "_last_kiosk_response",
        None,
    )

    if kiosk_response is not None:
        kiosk_response.message = agent_response
        return kiosk_response.model_dump()

    return {
        "screen": conversation_context.get("current_screen"),
        "message": agent_response or "Welcome to Burger King! What would you like to order?",
        "cart": conversation_context.get(
            "cart",
            [],
        ),
    }


@app.post("/cart/add")
def cart_add(request: AddToCartRequest):
    return cart_add_item(
        request.item_name,
        request.quantity,
    )


@app.post("/cart/clear")
def cart_clear():
    return clear_cart()


@app.post("/meal/options")
def meal_options(request: dict):
    item_id = request.get("item_id")

    if item_id is None:
        return {
            "success": False,
            "message": "item_id is required",
        }

    meal_flow = conversation_context.get(
        "meal_flow"
    )

    if (
        meal_flow
        and meal_flow.get("item_id") == item_id
        and meal_flow.get("status") == "declined"
    ):
        return {
            "success": True,
            "is_meal_available": False,
            "message": "Meal offer was declined.",
        }

    offer = get_meal_options(item_id)

    if not offer:
        return {
            "success": False,
            "message": "Meal not available.",
        }

    conversation_context["meal_flow"] = {
        "item_id": item_id,
        "status": "pending",
    }

    return offer


@app.post("/meal/decline")
def decline_meal():
    meal_flow = conversation_context.get(
        "meal_flow"
    )

    if not meal_flow:
        return {
            "success": False,
            "message": "No active meal flow.",
        }

    meal_flow["status"] = "declined"

    return {
        "success": True,
        "meal_flow": meal_flow,
    }


@app.post("/cart/add-meal")
def cart_add_meal(request: dict):
    return add_meal(
        request["meal"],
        request.get("quantity", 1),
    )


@app.patch("/cart/item")
def update_cart_item_endpoint(request: dict):
    return update_cart_item(
        request.get("item_index"),
        request.get("action"),
    )


@app.post("/order/complete")
def complete_order_endpoint():
    result = complete_order(
        conversation_context.get("cart", [])
    )

    return result


# ============================================================
# LOCAL KOKORO TEXT TO SPEECH
# ============================================================

_tts_cache: dict[str, bytes] = {}

@app.post("/tts")
def text_to_speech(request: dict):
    text = request.get("text")

    print("TTS REQUEST:", text)

    if not text:
        return Response(
            content=b"",
            media_type="audio/wav",
            status_code=400,
        )

    if text in _tts_cache:
        print("TTS CACHE HIT:", text[:30])
        return Response(
            content=_tts_cache[text],
            media_type="audio/wav",
        )

    try:
        print("GENERATING KOKORO AUDIO...")

        generator = tts_pipeline(
            text,
            voice="af_heart",
        )

        audio_segments = []

        for _, _, audio in generator:
            audio_segments.append(
                np.asarray(audio)
            )

        if not audio_segments:
            raise RuntimeError(
                "Kokoro generated no audio."
            )

        audio_data = np.concatenate(
            audio_segments
        )

        audio_buffer = io.BytesIO()

        sf.write(
            audio_buffer,
            audio_data,
            24000,
            format="WAV",
        )

        audio_buffer.seek(0)

        audio_bytes = audio_buffer.read()

        if len(_tts_cache) < 200:
            _tts_cache[text] = audio_bytes

        print(
            "KOKORO AUDIO GENERATED:",
            len(audio_bytes),
            "bytes",
        )

        return Response(
            content=audio_bytes,
            media_type="audio/wav",
        )

    except Exception as e:
        print(
            "KOKORO TTS ERROR:",
            repr(e),
        )

        return Response(
            content=b"TTS generation failed",
            media_type="text/plain",
            status_code=500,
        )


# ============================================================
# LOCAL WHISPER SPEECH TO TEXT
# ============================================================

@app.post("/stt")
async def speech_to_text(
    file: UploadFile = File(...)
):
    whisper_cli = os.path.expanduser(
        "~/whisper.cpp/build/bin/whisper-cli"
    )

    whisper_model = os.path.expanduser(
        "~/whisper.cpp/models/ggml-small.en.bin"
    )

    ffmpeg = "/opt/homebrew/bin/ffmpeg"

    print("\n" + "=" * 80)
    print("STT REQUEST")
    print("=" * 80)

    print(
        "WHISPER CLI:",
        whisper_cli,
    )

    print(
        "WHISPER MODEL:",
        whisper_model,
    )

    print(
        "FFMPEG:",
        ffmpeg,
    )

    print(
        "UPLOADED FILE:",
        file.filename,
    )

    print(
        "CONTENT TYPE:",
        file.content_type,
    )

    if not Path(whisper_cli).exists():
        print("ERROR: Whisper CLI not found.")

        return {
            "success": False,
            "message": "Whisper CLI not found.",
        }

    if not Path(whisper_model).exists():
        print("ERROR: Whisper model not found.")

        return {
            "success": False,
            "message": "Whisper model not found.",
        }

    if not Path(ffmpeg).exists():
        print("ERROR: FFmpeg not found.")

        return {
            "success": False,
            "message": "FFmpeg not found.",
        }

    try:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_dir = Path(temp_dir)

            input_file = temp_dir / "input.webm"
            wav_file = temp_dir / "input.wav"

            print("READING UPLOADED AUDIO...")

            audio_data = await file.read()

            print(
                "AUDIO SIZE:",
                len(audio_data),
                "bytes",
            )

            input_file.write_bytes(
                audio_data
            )

            print("STARTING FFMPEG...")

            ffmpeg_result = subprocess.run(
                [
                    ffmpeg,
                    "-y",
                    "-i",
                    str(input_file),
                    "-ar",
                    "16000",
                    "-ac",
                    "1",
                    "-c:a",
                    "pcm_s16le",
                    str(wav_file),
                ],
                capture_output=True,
                text=True,
                timeout=20,
            )

            print(
                "FFMPEG FINISHED:",
                ffmpeg_result.returncode,
            )

            if ffmpeg_result.returncode != 0:
                print(
                    "FFMPEG ERROR:"
                )

                print(
                    ffmpeg_result.stderr
                )

                return {
                    "success": False,
                    "message": "Audio conversion failed.",
                }

            print(
                "WAV CREATED:",
                wav_file.exists(),
            )

            if wav_file.exists():
                print(
                    "WAV SIZE:",
                    wav_file.stat().st_size,
                    "bytes",
                )

            print(
                "STARTING WHISPER..."
            )

            whisper_result = subprocess.run(
                [
                    whisper_cli,
                    "-m",
                    whisper_model,
                    "-f",
                    str(wav_file),
                    "-l",
                    "en",
                    "-nt",
                    "-np",
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )

            print(
                "WHISPER FINISHED:",
                whisper_result.returncode,
            )

            if whisper_result.stderr:
                print(
                    "WHISPER STDERR:"
                )

                print(
                    whisper_result.stderr
                )

            if whisper_result.returncode != 0:
                print(
                    "WHISPER ERROR"
                )

                return {
                    "success": False,
                    "message": "Speech recognition failed.",
                }

            transcript = (
                whisper_result.stdout
                .strip()
            )

            print(
                "WHISPER TRANSCRIPT:",
                transcript,
            )

            print("=" * 80 + "\n")

            return {
                "success": True,
                "text": transcript,
            }

    except subprocess.TimeoutExpired as e:
        print(
            "STT TIMEOUT:",
            repr(e),
        )

        return {
            "success": False,
            "message": "Speech recognition timed out.",
        }

    except Exception as e:
        print(
            "STT ERROR:",
            repr(e),
        )

        return {
            "success": False,
            "message": "Speech recognition failed.",
        }
