burgerSections = [
    {
        "id": "value-burgers",
        "title": "Value Burgers",
        "products": [
            {
                "id": 2,
                "name": "Crispy Veg",
                "shortDescription": "Crispy veg patty with onion & signature sauce.",
                "longDescription": "New Premium Black & White Sesame Bun with Crispy Veg Patty, Fresh Onion and Signature Sauce",
                "price": 59,
                "image": "src/assets/images/Burgers/Crispy Veg.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 3,
                "name": "Crispy Chicken",
                "shortDescription": "Crispy chicken patty with onion & signature sauce.",
                "longDescription": "New Premium Black & White Sesame Bun with Crispy Chicken Patty, Fresh Onion and Signature Sauce.Qty: 125 gms | Kcal: 299 | Carbs: 33 gms | Sugar: 5 gms | Fat: 13 gms | Saturated fat: 4 gms | Protein: 12.4 gms | Sodium: 405 mg",
                "price": 79,
                "image": "src/assets/images/Burgers/Crispy Chicken.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
            {
                "id": 4,
                "name": "Chicken Makhani",
                "shortDescription": "Crispy chicken patty with rich makhani sauce.",
                "longDescription": "New Premium Black and White Sesame Bun with Crispy Chicken Patty, Fresh Onion and Makhani Sauce. Qty: 125 gms | Kcal: 275 | Carbs: 35 gms | Sugar: 6 gms | Fat: 9 gms | Saturated fat: 4 gms | Protein: 13.3 gms | Sodium: 627 mg",
                "price": 89,
                "image": "src/assets/images/Burgers/Chicken Makhani.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
            {
                "id": 5,
                "name": "Veg Makhani",
                "shortDescription": "Veg patty with fresh onion & makhani sauce.",
                "longDescription": "New Premium Black & White Sesame Bun with Veg Patty, Fresh Onion and Makhani Sauce.",
                "price": 69,
                "image": "src/assets/images/Burgers/Veg Makhani.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 6,
                "name": "Crispy Veg Double Patty",
                "shortDescription": "Double crispy veg patties with signature sauce.",
                "longDescription": "Double up our best selling crispy veg burger",
                "price": 89,
                "image": "src/assets/images/Burgers/Crispy Veg Double Patty.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 7,
                "name": "Crispy Chicken Double Patty",
                "shortDescription": "Double crispy chicken patties for extra crunch.",
                "longDescription": "Double up the crispy chicken patty burger.Qty: 183 gms | Kcal: 429 | Carbs: 41 gms| Sugar: 6 gms| Fat: 21 gms| Saturated fat: 8 gms| Protein: 20.4 gms| Sodium: 638 mg",
                "price": 119,
                "image": "src/assets/images/Burgers/Crispy Chicken Double Patty.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
        ],
    },

    {
        "id": "whoppers",
        "title": "Whoppers",
        "products": [
            {
                "id": 8,
                "name": "Veg Whopper",
                "shortDescription": "XL veg whopper with fresh veggies & smoky sauces.",
                "longDescription": "XL Size Original Whopper Veg in premium glaze bun. 7 layers of taste: Extra Crunchy Veg patty, fresh onion, crispy lettuce, juicy tomatoes (seasonal), tangy gherkins, creamy & smoky sauces.Qty: 303 gms | Kcal: 367 | Carbs: 48 gms| Sugar: 11 gms| Fat: 13 gms| Saturated fat: 3 gms| Protein: 16 gms| Sodium: 761 mg",
                "price": 189,
                "image": "src/assets/images/Burgers/Veg Whopper.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 9,
                "name": "Chicken Whopper",
                "shortDescription": "Flame-grilled chicken with fresh veggies & sauces.",
                "longDescription": "XL Size Original Whopper Chicken in premium glaze bun. 7 layers of taste: Flame Grill Chicken patty, fresh onion, crispy lettuce, juicy tomatoes (seasonal), tangy gherkins, creamy & smoky sauces.Qty: 280 Gms| Kcal: 667.2 | Carbs 59.1 Gms| Sugar: 8.7 Gms| Fat: 36.3 Gms| Saturated fat: 8.1 Gms| Protein: 26.2 Gms| Sodium: 1018.7 Mg Contains: Gluten, Soybean, Milk, Sesame seeds.",
                "price": 209,
                "image": "src/assets/images/Burgers/Chicken Whopper.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
            {
                "id": 10,
                "name": "Grill Chicken Whopper",
                "shortDescription": "Flame-grilled chicken, lettuce & smoky sauces.",
                "longDescription": "Regular Size premium glaze bun with 7 layers of taste: Flame-Grilled Chicken patty, fresh onion, crispy lettuce, juicy tomatoes (seasonal) tangy gherkins, creamy & smoky sauces.Qty: 179 gms | Kcal: 327 | Carbs: 35 gms| Sugar: 1 gms| Fat: 14 gms| Saturated fat: 3 gms| Protein: 14.3 gms| Sodium: 952 mg",
                "price": 169,
                "image": "src/assets/images/Burgers/Grill Chicken Whopper.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
            {
                "id": 11,
                "name": "Paneer Whopper",
                "shortDescription": "Crunchy paneer patty with fresh veggies.",
                "longDescription": "Reg. size bun with 7 layers of taste: Crunchy Soft Paneer patty, fresh onion, crispy lettuce, juicy tomatoes (seasonal), tangy gherkins, creamy & smoky sauces.Qty: 197 gms | Kcal: 472 | Carbs: 43 gms| Sugar: 8 gms| Fat: 27 gms| Saturated fat: 13 gms| Protein: 16.4 gms| Sodium: 1042 mg",
                "price": 169,
                "image": "src/assets/images/Burgers/Paneer Whopper.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 12,
                "name": "Cheese Whopper",
                "shortDescription": "Cheese lava patty with fresh veggies & sauces.",
                "longDescription": "Reg. size bun with 7 layers of taste: Molten Cheese Lava patty, fresh onion, crispy lettuce, juicy tomatoes (seasonal), tangy gherkins, creamy & smoky sauces.Qty: 201 gms | Kcal: 516 | Carbs: 47 gms| Sugar: 8 gms| Fat: 30 gms| Saturated fat: 13 gms| Protein: 15.3 gms| Sodium: 1530 mg",
                "price": 179,
                "image": "src/assets/images/Burgers/Cheese Whopper.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
        ],
    },

        {
        "id": "premium-burgers",
        "title": "Premium Burgers",
        "products": [
            {
                "id": 16,
                "name": "Paneer Royale",
                "shortDescription": "Paneer patty with signature sauces in brioche buns.",
                "longDescription": "60 gm Paneer Patty, Sauces In premium Brioche Buns.Qty: 253 gms | Kcal: 600 | Carbs: 58 gms| Sugar: 10 gms| Fat: 33 gms| Saturated fat: 14 gms| Protein: 20.8 gms| Sodium: 1314 mg",
                "price": 209,
                "image": "src/assets/images/Burgers/Paneer Royale.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
        ],
    },

    {
        "id": "crazy-deals",
        "title": "Crazy Deals",
        "products": [
            {
                "id": 17,
                "name": "BK Veggie",
                "shortDescription": "Mix veg patty, lettuce, tomato & mayo.",
                "longDescription": "New Premium Black & White Sesame Bun with Mix Veg Patty, Lettuce, Tomato(Seasonal) & Our Signature Mayo.",
                "price": 139,
                "image": "src/assets/images/Burgers/BK Veggie.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 18,
                "name": "BK Chicken",
                "shortDescription": "Crunchy chicken patty with lettuce & mayo.",
                "longDescription": "New Premium Black & White Sesame Bun with Crunchy Chicken Patty, Lettuce,Tomatoes(seasonal) & Our Signature Mayo.Qty: 163 gms | Kcal: 333 | Carbs: 41 gms| Sugar: 5 gms| Fat: 13 gms| Saturated fat: 5 gms| Protein: 13.7 gms| Sodium: 347 mg",
                "price": 139,
                "image": "src/assets/images/Burgers/BK Chicken.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
        ],
    },

    {
        "id": "wraps-and-tacos",
        "title": "Wraps and Tacos",
        "products": [
            {
                "id": 24,
                "name": "Crunchy Veg Taco",
                "shortDescription": "Crunchy taco with beans, veggies & secret sauce.",
                "longDescription": "Be ready for a crunchy, saucy, explosion. A crunchy taco shell filled with beans & veg mix, chef's secret sauce, fresh onion & crisp lettuce.",
                "price": 79,
                "image": "src/assets/images/Burgers/Crunchy Veg Taco.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 25,
                "name": "Crunchy Chicken Taco",
                "shortDescription": "Crunchy taco with chicken patty & spicy sauce.",
                "longDescription": "Crunchy Shell with chicken patty, crunchy veggies and spicy sauce.",
                "price": 99,
                "image": "src/assets/images/Burgers/Crunchy Chicken Taco.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
            {
                "id": 26,
                "name": "BK Veg Pizza Puff",
                "shortDescription": "Crispy puff with cheesy veggie pizza filling.",
                "longDescription": "Crispy and flaky puff pastry loaded with a delicious pizza-style filling of rich tomato sauce, sweet corn, carrots, bell peppers, and melted cheesy goodness. Baked to golden perfection for a crunchy bite and authentic pizza flavors in every mouthful.",
                "price": 45,
                "image": "src/assets/images/Burgers/BK Veg Pizza Puff.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 27,
                "name": "Paneer Royale Wrap",
                "shortDescription": "Loaded wrap with paneer, veggies & sauces.",
                "longDescription": "Loaded wrap with thick paneer patty, lots of veggies and sauces.Qty: 229 gms | Kcal: 406 | Carbs: 63 gms| Sugar: 18 gms| Fat: 33 gms| Saturated fat: 13 gms| Protein: 16.6 gms| Sodium: 763 mg",
                "price": 189,
                "image": "src/assets/images/Burgers/Paneer Royale Wrap.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
        ],
    },

        {
        "id": "peri-peri",
        "title": "Peri Peri",
        "products": [
            {
                "id": 135,
                "name": "Peri Peri Veg",
                "shortDescription": "Spicy grilled veg burger with fresh vegetables.",
                "longDescription": "XL size 7 layer Veg Whopper with crunchy veg patty dunked in hot & spicy Peri Peri glaze with herby mayo in premium glazed buns for authentic Peri Peri flavours",
                "price": 199,
                "image": "src/assets/images/Burgers/Peri Peri Veg.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 136,
                "name": "Peri Peri Chicken",
                "shortDescription": "Juicy grilled chicken burger with fresh vegetables.",
                "longDescription": "XL size 7 layer Grill Chicken Whopper with grill chicken patty dunked in hot & spicy Peri Peri glaze with herby mayo in premium glazed buns for authentic Peri Peri flavours",
                "price": 239,
                "image": "src/assets/images/Burgers/Peri Peri Chicken.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
            {
                "id": 137,
                "name": "Peri Peri Paneer",
                "shortDescription": "Spicy peri peri paneer burger with fresh vegetables.",
                "longDescription": "Crispy paneer patty dunked in hot & spicy Peri Peri glaze with herby mayo in premium brioche buns for authentic Peri Peri flavours",
                "price": 219,
                "image": "src/assets/images/Burgers/Peri Peri Paneer.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 138,
                "name": "Peri Peri Cheese",
                "shortDescription": "Spicy cheese burger with fresh vegetables.",
                "longDescription": "Molten Cheese Lava patty dunked in hot & spicy Peri Peri glaze with herby mayo in premium brioche buns for authentic Peri Peri flavours.",
                "price": 239,
                "image": "src/assets/images/Burgers/Peri Peri Cheese.png",
                "foodType": "veg",
                "isMealAvailable": True,
            },
            {
                "id": 139,
                "name": "Peri Peri Chicken Burger",
                "shortDescription": "Spicy peri peri chicken burger with fresh vegetables.",
                "longDescription": "Crispy Juicy whole-muscle chicken patty dunked in hot & spicy Peri Peri glaze with herby mayo in premium brioche bun for authentic Peri Peri flavours",
                "price": 229,
                "image": "src/assets/images/Burgers/Peri Peri Chicken Burger.png",
                "foodType": "nonveg",
                "isMealAvailable": True,
            },
        ],
    },
]