dessertSections = [
    {
        "id": "soft-serve",
        "title": "Soft Serve",
        "products": [
            {
                "id": 55,
                "name": "Vanilla Softie",
                "shortDescription": "Creamy vanilla soft serve in a crispy cone.",
                "longDescription": "Ice cream with cone. Anytime happiness.",
                "price": 33,
                "image": "src/assets/images/Dessert/Vanilla Softie.png",
                "foodType": "veg",
            },
            {
                "id": 56,
                "name": "Choco Dip Softie",
                "shortDescription": "Vanilla soft serve coated with rich chocolate.",
                "longDescription": "Ice cream dipped in chocolate.",
                "price": 50,
                "image": "src/assets/images/Dessert/Choco Dip Softie.png",
                "foodType": "veg",
            },
        ],
    },

    {
        "id": "waffle-cones",
        "title": "Waffle Cones",
        "products": [
            {
                "id": 57,
                "name": "Vanilla Softie Waffle Cone",
                "shortDescription": "Creamy vanilla soft serve in a crunchy waffle cone.",
                "longDescription": "Vanilla Softie with crunchy Waffle Cone. Delicious crunchy happinessQty: 80 gms| Kcal: 77 | Carbs: 10.7 gms| Sugar: 9.3 gms| Fat: 3.3 gms| Saturated fat: 1.8 gms| Protein: 1.8 gms|",
                "price": 38,
                "image": "src/assets/images/Dessert/Vanilla Softie Waffle Cone.png",
                "foodType": "veg",
            },
            {
                "id": 58,
                "name": "Choco Dip Softie Waffle Cone",
                "shortDescription": "Chocolate-coated soft serve in a crunchy waffle cone.",
                "longDescription": "Choco Dip Softie with crunchy Waffle Cone. Delicious crunchy happiness.Qty: 95 gms| Kcal: 172 | Carbs: 17.1 gms| Sugar: 15.1 gms| Fat: 10.5 gms| Saturated fat: 7.4 gms| Protein: 2.4 gms|",
                "price": 55,
                "image": "src/assets/images/Dessert/Choco Dip Softie Waffle Cone.png",
                "foodType": "veg",
            },
        ],
    },

    {
        "id": "sundaes",
        "title": "Sundaes",
        "products": [
            {
                "id": 59,
                "name": "Mango Sundae",
                "shortDescription": "Creamy vanilla sundae topped with sweet mango sauce.",
                "longDescription": "Ice cream served with mango puree.",
                "price": 45,
                "image": "src/assets/images/Dessert/Mango sundae.png",
                "foodType": "veg",
            },
            {
                "id": 60,
                "name": "Black Currant Sundae",
                "shortDescription": "Creamy vanilla sundae topped with black currant sauce.",
                "longDescription": "Icrecream with black currant sauce.",
                "price": 69,
                "image": "src/assets/images/Dessert/Black Currant sundae.png",
                "foodType": "veg",
            },
            {
                "id": 61,
                "name": "Chocolate Sundae",
                "shortDescription": "Creamy vanilla sundae topped with rich chocolate fudge.",
                "longDescription": "Ice cream with hot chocolate fudge.",
                "price": 45,
                "image": "src/assets/images/Dessert/Chocolate sundae.png",
                "foodType": "veg",
            },
            {
                "id": 62,
                "name": "BK Fusion Sundae (made with KitKat)",
                "shortDescription": "Creamy vanilla sundae topped with crunchy KitKat pieces.",
                "longDescription": "Creamy vanilla sundae topped with delicious KitKat pieces for the perfect chocolate crunch.",
                "price": 79,
                "image": "src/assets/images/Dessert/BK Fusion Sundae (made with KitKat).png",
                "foodType": "veg",
            },
        ],
    },

    {
        "id": "special-desserts",
        "title": "Special Desserts",
        "products": [
            {
                "id": 63,
                "name": "Cookie Crunch Sundae",
                "shortDescription": "Chocolate sundae topped with crunchy cookie crumbs.",
                "longDescription": "Ice cream with cookie crumb & hot chocolate fudge.",
                "price": 69,
                "image": "src/assets/images/Dessert/Cookie Crunch Sundae.png",
                "foodType": "veg",
            },
            {
                "id": 64,
                "name": "Chocolate Mousse Cup",
                "shortDescription": "Smooth chocolate mousse topped with ganache and choco chips.",
                "longDescription": "Airy and creamy chocolate mousse topped with chocolate ganache and choco chips.",
                "price": 129,
                "image": "src/assets/images/Dessert/Chocolate Mousse Cup.png",
                "foodType": "veg",
            },
            {
                "id": 65,
                "name": "Choco Lava Cup",
                "shortDescription": "Soft chocolate cake with a rich molten center.",
                "longDescription": "Melty Chocolate filled in cupcake.",
                "price": 119,
                "image": "src/assets/images/Dessert/Choco Lava Cup.png",
                "foodType": "veg",
            },
        ],
    },
]