drinkSections = [
    {
        "id": "bk-cafe",
        "title": "BK Café",
        "products": [
            {
                "id": 109,
                "name": "Classic Cold Coffee",
                "shortDescription": "Refreshing classic cold coffee with milk.",
                "longDescription": "Our signature BK Café Coffee ice blended with milk & cream.",
                "price": 189,
                "image": "src/assets/images/Drinks/Classic Cold Coffee.png",
                "type": "cold",
            },
            {
                "id": 110,
                "name": "Iced Latte",
                "shortDescription": "Chilled espresso blended with creamy milk.",
                "longDescription": "100% Arabica Espresso poured over milk and ice.",
                "price": 199,
                "image": "src/assets/images/Drinks/Iced Latte.png",
                "type": "cold",
            },
            {
                "id": 111,
                "name": "Mocha Frappe",
                "shortDescription": "Chocolate coffee frappe topped with vanilla soft serve.",
                "longDescription": "Chocolate flavoured Cold Coffee topped with Vanilla Softie.Qty: 355 gms| Kcal: 293 | Carbs: 52.2 gms| Sugar: 45.7 gms| Fat: 7.5 gms| Saturated fat: 5.5 gms| Protein: 4.3 gms|",
                "price": 249,
                "image": "src/assets/images/Drinks/Mocha Frappe.png",
                "type": "cold",
            },
            {
                "id": 112,
                "name": "Espresso (Single Shot)",
                "shortDescription": "Bold single shot of rich espresso.",
                "longDescription": "Rich Shot of our signature BK Café Coffee without milk.",
                "price": 109,
                "image": "src/assets/images/Drinks/Espresso (Single Shot).png",
                "type": "hot",
            },
            {
                "id": 118,
                "name": "Espresso (Double Shot)",
                "shortDescription": "Bold double shot of rich espresso.",
                "longDescription": "Rich Shot of our signature BK Café Coffee without milk.",
                "price": 109,
                "image": "src/assets/images/Drinks/Espresso (Double Shot).png",
                "type": "hot",
            },
            {
                "id": 119,
                "name": "Americano (Small)",
                "shortDescription": "Small serving of rich Americano.",
                "longDescription": "Our signature BK Café Coffee with Sweet Caramel Flavour.",
                "price": 189,
                "image": "src/assets/images/Drinks/Americano (Small).png",
                "type": "hot",
            },
            {
                "id": 113,
                "name": "Americano (Regular)",
                "shortDescription": "Rich espresso with hot water.",
                "longDescription": "Our signature BK Café Coffee with Sweet Caramel Flavour.",
                "price": 189,
                "image": "src/assets/images/Drinks/Americano (Regular).png",
                "type": "hot",
            },
            {
                "id": 120,
                "name": "Iced Americano",
                "shortDescription": "Refreshing iced Americano coffee.",
                "longDescription": "Our signature Arabica espresso with ice.",
                "price": 159,
                "image": "src/assets/images/Drinks/Iced Americano.png",
                "type": "cold",
            },
            {
                "id": 121,
                "name": "Cafe Latte (Small)",
                "shortDescription": "Small creamy latte with steamed milk.",
                "longDescription": "Our signature BK Café Coffee with steamed milk.",
                "price": 159,
                "image": "src/assets/images/Drinks/Cafe Latte (Small).png",
                "type": "hot",
            },
            {
                "id": 114,
                "name": "Cafe Latte (Regular)",
                "shortDescription": "Smooth espresso with steamed milk.",
                "longDescription": "Our signature BK Café Coffee with steamed milk.",
                "price": 189,
                "image": "src/assets/images/Drinks/Cafe Latte (Regular).png",
                "type": "hot",
            },
            {
                "id": 115,
                "name": "Cappuccino (Small)",
                "shortDescription": "Creamy cappuccino with milk foam.",
                "longDescription": "Our signature BK Café Coffee with steamed milk & milk froth.",
                "price": 149,
                "image": "src/assets/images/Drinks/Cappuccino (Small).png",
                "type": "hot",
            },
            {
                "id": 122,
                "name": "Cappuccino (Regular)",
                "shortDescription": "Regular cappuccino with milk foam.",
                "longDescription": "Espresso with steamed milk & milk froth.",
                "price": 179,
                "image": "src/assets/images/Drinks/Cappuccino (Regular).png",
                "type": "hot",
            },
            {
                "id": 116,
                "name": "Mocha Cappuccino (Small)",
                "shortDescription": "Chocolate cappuccino with rich mocha flavor.",
                "longDescription": "Our signature BK Café Coffee with Rich Chocolate Flavour.",
                "price": 195,
                "image": "src/assets/images/Drinks/Mocha Cappuccino (Small).png",
                "type": "hot",
            },
            {
                "id": 123,
                "name": "Mocha Cappuccino (Regular)",
                "shortDescription": "Regular mocha cappuccino with chocolate flavor.",
                "longDescription": "Rich Chocolate Flavoured Coffee.",
                "price": 219,
                "image": "src/assets/images/Drinks/Mocha Cappuccino (Regular).png",
                "type": "hot",
            },
            {
                "id": 117,
                "name": "Hot Chocolate",
                "shortDescription": "Creamy hot chocolate made with rich cocoa.",
                "longDescription": "The chocolate which you can drink. Rich Creamy Chocolate with steamed milk.",
                "price": 179,
                "image": "src/assets/images/Drinks/Hot Chocolate.png",
                "type": "hot",
            },
        ],
    },
        {
        "id": "cold-drinks",
        "title": "Cold Drinks",
        "products": [
            {
                "id": 124,
                "name": "Coca Cola (Medium)",
                "shortDescription": "Classic chilled Coca-Cola soft drink.",
                "longDescription": "Coca Cola.",
                "price": 111,
                "image": "src/assets/images/Drinks/Coca Cola.png",
                "type": "cold",
            },
            {
                "id": 224,
                "name": "Coca Cola (Large)",
                "shortDescription": "Large classic chilled Coca-Cola soft drink.",
                "longDescription": "Coca Cola.",
                "price": 131,
                "image": "src/assets/images/Drinks/Coca Cola.png",
                "type": "cold",
            },
            {
                "id": 125,
                "name": "Sprite (Medium)",
                "shortDescription": "Refreshing lemon-lime soft drink.",
                "longDescription": "Sprite.",
                "price": 111,
                "image": "src/assets/images/Drinks/Sprite.png",
                "type": "cold",
            },
            {
                "id": 225,
                "name": "Sprite (Large)",
                "shortDescription": "Large refreshing lemon-lime soft drink.",
                "longDescription": "Sprite.",
                "price": 131,
                "image": "src/assets/images/Drinks/Sprite.png",
                "type": "cold",
            },
            {
                "id": 126,
                "name": "Fanta (Medium)",
                "shortDescription": "Refreshing orange flavored soft drink.",
                "longDescription": "Fanta.",
                "price": 111,
                "image": "src/assets/images/Drinks/Fanta.png",
                "type": "cold",
            },
            {
                "id": 226,
                "name": "Fanta (Large)",
                "shortDescription": "Large refreshing orange flavored soft drink.",
                "longDescription": "Fanta.",
                "price": 131,
                "image": "src/assets/images/Drinks/Fanta.png",
                "type": "cold",
            },
            {
                "id": 227,
                "name": "Thums Up (Medium)",
                "shortDescription": "Bold and fizzy cola drink.",
                "longDescription": "Thums Up.",
                "price": 111,
                "image": "src/assets/images/Drinks/Large Thums Up.png",
                "type": "cold",
            },
            {
                "id": 127,
                "name": "Thums Up (Large)",
                "shortDescription": "Large bold and fizzy cola drink.",
                "longDescription": "Thums Up.",
                "price": 131,
                "image": "src/assets/images/Drinks/Large Thums Up.png",
                "type": "cold",
            },
            {
                "id": 128,
                "name": "Masala Fizz",
                "shortDescription": "Sparkling masala flavored fizzy drink.",
                "longDescription": "A fizzy twist to your favourite Coke — now with full on Masala flavour.Qty: 450ml| Kcal: 88.34 | Carbs: 22.08 gms| Sugar: 22.07 gms| Fat: 0.0 gms| Saturated fat: 0 gms| Protein: 0.0 gms| Sodium: 734.00 mg",
                "price": 129,
                "image": "src/assets/images/Drinks/Masala Fizz.png",
                "type": "cold",
            },
        ],
    },
        {
        "id": "floats",
        "title": "Floats",
        "products": [
            {
                "id": 129,
                "name": "Cola Float",
                "shortDescription": "Classic cola with vanilla soft serve.",
                "longDescription": "Coke + Ice Cream = Bliss.",
                "price": 52,
                "image": "src/assets/images/Drinks/Cola Float.png",
                "type": "cold",
            },
            {
                "id": 130,
                "name": "Fanta Float",
                "shortDescription": "Refreshing Fanta with vanilla soft serve.",
                "longDescription": "Fanta + Ice Cream = Bliss.",
                "price": 52,
                "image": "src/assets/images/Drinks/Fanta Float.png",
                "type": "cold",
            },
        ],
    },

    {
        "id": "shakes",
        "title": "Shakes",
        "products": [
            {
                "id": 131,
                "name": "Berry Blast Shake",
                "shortDescription": "Creamy black currant thick shake.",
                "longDescription": "Rich Creamy Black Currant Thick shake.",
                "price": 189,
                "image": "src/assets/images/Drinks/Berry Blast Shake.png",
                "type": "cold",
            },
            {
                "id": 132,
                "name": "Mango Shake",
                "shortDescription": "Rich and creamy mango thick shake.",
                "longDescription": "Rich Creamy Mango Thick shake.",
                "price": 189,
                "image": "src/assets/images/Drinks/Mango Shake.png",
                "type": "cold",
            },
            {
                "id": 133,
                "name": "Chocolate Shake",
                "shortDescription": "Rich and creamy chocolate thick shake.",
                "longDescription": "Rich Creamy Chocolate Thick shake.",
                "price": 189,
                "image": "src/assets/images/Drinks/Chocolate Shake.png",
                "type": "cold",
            },
            {
                "id": 134,
                "name": "KitKat Shake",
                "shortDescription": "Creamy KitKat blended thick shake.",
                "longDescription": "Made with Kit Kat, enjoy our rich creamy fusion thick shake.Qty: 378ml| Kcal: 591 | Carbs: 92 gms| Sugar: 77 gms| Fat: 20 gms| Saturated fat: 15 gms| Protein: 10.6 gms| Sodium: 270 mg",
                "price": 249,
                "image": "src/assets/images/Drinks/KitKat Shake.png",
                "type": "cold",
            },
        ],
    },
]