sideSections = [
    {
        "id": "fries",
        "title": "Fries",
        "products": [
            {
                "id": 66,
                "name": "Fries (Medium)",
                "shortDescription": "Golden crispy fries.",
                "longDescription": "Perfectly salted golden potato fries, fried until crispy on the outside and fluffy on the inside. A classic side that pairs perfectly with any burger or beverage.",
                "price": 130,
                "image": "src/assets/images/sides/Fries (Medium).png",
                "foodType": "veg",
            },
            {
                "id": 67,
                "name": "Fries (King)",
                "shortDescription": "Extra-large crispy fries.",
                "longDescription": "A king-sized portion of golden crispy fries, seasoned to perfection and ideal for sharing or satisfying bigger cravings.",
                "price": 140,
                "image": "src/assets/images/sides/Fries (King).png",
                "foodType": "veg",
            },
            {
                "id": 68,
                "name": "Peri Peri Fries (Medium)",
                "shortDescription": "Fries with peri peri seasoning.",
                "longDescription": "Crispy golden fries tossed in a bold peri peri spice blend that delivers the perfect combination of heat and flavor.",
                "price": 149,
                "image": "src/assets/images/sides/Peri Peri Fries (Medium).png",
                "foodType": "veg",
            },
            {
                "id": 69,
                "name": "Peri Peri Fries (King)",
                "shortDescription": "King-size peri peri fries.",
                "longDescription": "A larger serving of crispy fries generously coated in spicy peri peri seasoning for an irresistible kick.",
                "price": 154,
                "image": "src/assets/images/sides/Peri Peri Fries (King).png",
                "foodType": "veg",
            },
            {
                "id": 70,
                "name": "Saucy Fries",
                "shortDescription": "Loaded fries with sauce.",
                "longDescription": "Crunchy fries topped with Burger King's signature creamy sauce, creating a rich and indulgent snacking experience.",
                "price": 139,
                "image": "src/assets/images/sides/Saucy Fries.png",
                "foodType": "veg",
            },
        ],
    },

    {
        "id": "nuggets",
        "title": "Nuggets",
        "products": [
            {
                "id": 72,
                "name": "Crunchy Chicken Nuggets (4 Pc)",
                "shortDescription": "4 crispy chicken nuggets, golden and crunchy.",
                "longDescription": "Tender chicken nuggets coated in a golden crunchy crumb and cooked to perfection for a satisfying bite every time.",
                "price": 89,
                "image": "src/assets/images/sides/Crunchy Chicken Nuggets (4 Pc).png",
                "foodType": "nonveg",
            },
            {
                "id": 73,
                "name": "(6Pc) Crunchy Chicken Nuggets + 1 Dip",
                "shortDescription": "6 crispy chicken nuggets served with 1 delicious dip.",
                "longDescription": "Six juicy chicken nuggets wrapped in a crunchy coating and served hot for a delicious snack or side.",
                "price": 189,
                "image": "src/assets/images/sides/(6Pc) Crunchy Chicken Nuggets + 1 Dip.png",
                "foodType": "nonveg",
            },
            {
                "id": 74,
                "name": "(9Pc) Crunchy Chicken Nuggets + 2 Dips",
                "shortDescription": "9 crispy chicken nuggets served with 2 delicious dips.",
                "longDescription": "A generous serving of crispy chicken nuggets made with tender chicken and a crunchy golden crust.",
                "price": 309,
                "image": "src/assets/images/sides/(9Pc) Crunchy Chicken Nuggets + 2 Dips.png",
                "foodType": "nonveg",
            },
            {
                "id": 75,
                "name": "(18Pc) Crunchy Chicken Nuggets + 3 Dips",
                "shortDescription": "18 crispy chicken nuggets served with 3 delicious dips.",
                "longDescription": "Perfect for sharing, these crunchy chicken nuggets offer juicy chicken wrapped in a flavorful golden coating.",
                "price": 359,
                "image": "src/assets/images/sides/(18Pc) Crunchy Chicken Nuggets + 3 Dips.png",
                "foodType": "nonveg",
            },
            {
                "id": 140,
                "name": "Peri Peri Chicken Nuggets 4 Pc",
                "shortDescription": "Crispy peri peri chicken bites with spicy sauce.",
                "longDescription": "Tender Juicy Crunchy Chicken Nuggets fried to golden perfection topped with Peri Peri Glaze.",
                "price": 109,
                "image": "src/assets/images/sides/Peri Peri Chicken Nuggets 4 Pc.png",
                "foodType": "nonveg",
            },
            {
                "id": 141,
                "name": "Peri Peri Chicken Nuggets 6 Pc",
                "shortDescription": "Crispy peri peri chicken bites with spicy sauce.",
                "longDescription": "Tender Juicy Crunchy Chicken Nuggets fried to golden perfection topped with Peri Peri Glaze.",
                "price": 169,
                "image": "src/assets/images/sides/Peri Peri Chicken Nuggets 6 Pc.png",
                "foodType": "nonveg",
            },
            {
                "id": 142,
                "name": "Peri Peri Chicken Wings 4pc",
                "shortDescription": "Spicy peri peri chicken wings with bold seasoning.",
                "longDescription": "Chicken Wings dunked in hot and spicy peri peri glaze.",
                "price": 209,
                "image": "src/assets/images/sides/Peri Peri Chicken Wings 4pc.png",
                "foodType": "nonveg",
            },
            {
                "id": 143,
                "name": "Peri Peri Chicken Boneless 4pc",
                "shortDescription": "Spicy peri peri chicken bites with rich seasoning.",
                "longDescription": "Boneless chicken dunked in hot and spicy peri peri glaze.",
                "price": 199,
                "image": "src/assets/images/sides/Peri Peri Chicken Boneless 4pc.png",
                "foodType": "nonveg",
            },
            {
                "id": 144,
                "name": "Peri Peri Chicken Boneless 7pc",
                "shortDescription": "Juicy peri peri chicken bites with bold spices.",
                "longDescription": "Boneless chicken dunked in hot and spicy peri peri glaze.",
                "price": 309,
                "image": "src/assets/images/sides/Peri Peri Chicken Boneless 7pc.png",
                "foodType": "nonveg",
            },
            {
                "id": 145,
                "name": "Chicken Wings - Fried (8 Pcs)",
                "shortDescription": "Crispy fried chicken bucket with golden crunch.",
                "longDescription": "Juicy chicken wings cooked to perfection.",
                "price": 279,
                "image": "src/assets/images/sides/Chicken Wings - Fried (8 Pcs).png",
                "foodType": "nonveg",
            },
            {
                "id": 146,
                "name": "Chicken Wings - Fried (15 Pcs)",
                "shortDescription": "Crunchy fried chicken pieces.",
                "longDescription": "Juicy chicken wings cooked to perfection.",
                "price": 519,
                "image": "src/assets/images/sides/Chicken Wings - Fried (15 Pcs).png",
                "foodType": "nonveg",
            },
        ],
    },
        {
        "id": "veggie-sides",
        "title": "Veggie Sides",
        "products": [
            {
                "id": 78,
                "name": "Veggie Strips (5 Pc)",
                "shortDescription": "5 crispy veggie strips.",
                "longDescription": "Delicious vegetable strips coated in a crunchy golden crumb and fried until perfectly crisp.",
                "price": 55,
                "image": "src/assets/images/sides/Veggie Strips (5 Pc).png",
                "foodType": "veg",
            },
            {
                "id": 80,
                "name": "Masala Hashbrown",
                "shortDescription": "Crispy masala hashbrown.",
                "longDescription": "Golden hashbrown infused with flavorful Indian spices and fried to crispy perfection.",
                "price": 45,
                "image": "src/assets/images/sides/Masala Hashbrown.png",
                "foodType": "veg",
            },
        ],
    },

    {
        "id": "dips",
        "title": "Dips",
        "products": [
            {
                "id": 81,
                "name": "Fiery Hell Dip",
                "shortDescription": "Extra spicy dip.",
                "longDescription": "A bold and fiery dipping sauce crafted for spice lovers who enjoy an intense burst of heat with every bite.",
                "price": 25,
                "image": "src/assets/images/sides/Fiery Hell Dip.png",
                "foodType": "veg",
            },
            {
                "id": 82,
                "name": "Chilli Sauce With Oregano",
                "shortDescription": "Classic chilli oregano dip.",
                "longDescription": "A flavorful blend of chilli sauce and aromatic oregano that enhances the taste of fries, nuggets, and sides.",
                "price": 25,
                "image": "src/assets/images/sides/Chilli Sauce With Oregano.png",
                "foodType": "veg",
            },
        ],
    },
]
